--0ambidextrous
--0ambivalent
ambi,两边,周围
ambidextrous,双手灵巧的
ambidextrous,左右手都灵活的
ambience,环境
ambiguity
ambiguity,含糊,不明确
ambiguity,模糊
ambiguous
ambiguous,含糊的,模棱两可的
ambiguous,模棱两可的
ambiguous,模棱两可的,含糊其词的
ambition
ambition(野心),古代政客四处拉票的行为
ambition,[æm'bɪʃ(ə)n]n,野心,雄心,抱负vi,追求,有……的野心
ambition,目标
ambition,野心,雄心
ambitious,[æm'bɪʃəs]adj,野心勃勃的,有雄心的,
ambitious,有雄心的,野心勃勃的
ambit,界限
ambivalence
ambivalence,矛盾情绪
ambivalent,模糊的
ambivalent,矛盾的
amble
amble,['æmb(ə)l]n,缓行,从容漫步
ambulance(救护车),战场上流动的医院
ambulance,['æmbjʊl(ə)ns]n,救护车,流动医院,
dis,不,非,使相反,ambiguity,歧义,即不再有歧义,消除歧义,
disambiguate,使消除歧义
perambulate,遍歷
preamble
【发音释义】,[,æmbɪ'dekstrəs]adj,双手灵巧的,左右逢源的,两面派的
【发音释义】,[æm'bɪgjʊəs]adj,模棱两可的,引起歧义的
【发音释义】,[æm'bɪvələns]n,矛盾情绪,正反感情并存
【发音释义】,[æm'bɪvələnt]adj,矛盾的,好恶相克的
ambiguity(模棱两可的话,含糊)
ambiguous(模棱两可的),dexterous(灵巧的),dexterity(灵巧)
value(价值),valiant(英勇的的),Valentine(瓦伦丁),Valentia(瓦伦西亚)
【结构分析】,ambidextrous=ambi(全都)dextr(灵巧的)ous(形容词后缀)→(双手)全都灵巧的
【结构分析】,ambiguous=ambi(四处)gu(带领)ous(形容词后缀)→四处漫游的→指向不明的,模棱两可的
【结构分析】,ambivalence=ambi(两边)valence(力量)→正反两个方向的力量→矛盾情绪
【结构分析】,ambivalent=ambivalen(ce)t(形容词后缀)→矛盾的
【背景知识】,古代人认为右手比较灵活,所以dexter一词既表示“右手的”又表示“灵活的”,right(正确的)一词的本意也是“右手的”,
【衍生词】,ambidexterity(双手俱灵巧,两面派手法)
【衍生词】,ambivalent(矛盾的)
【词源解释】,ambi←拉丁语ambi(四处,周围),dextr←拉丁语dexter(右手的,灵巧的)
【词源解释】,ambi←拉丁语ambi(四处,周围),gu←拉丁语agere(带领)
【词源解释】,ambi←拉丁语ambi(四处,周围),valence←拉丁语valentia(力量)
使用ambiguous一词的第一人似乎是英国人文主义者奠尔(SirThomasMore,14771535),他在《关于异端的对话》(ADiaLogueConcerningHeresies,1528)一书中写道,“IfitwerenowdoubtfulandambiguouswhetherthechurchofChristwereintherightruleofdoctrineornot,”该词来自拉丁语ambiguus‘doubtful’,而ambiguus又是从动词ambigere‘go／driveround’派生出来的,其成分ambi含有bothways(二者,二)之意,故ambiguous被用以表示“模棱两可的”或“含糊其词的”,ambi已被作为前缀吸收到英语中来,用以构成新词,如ambisextrous(不分男女的,对两性都有吸引力的),ambidextrous(两手都善用的)等,
前缀ambi,两边,词根dext,右手,指灵活,
前缀ambi,两边,词根ig,同ag,做,
前缀ambi,两边,词根val,力量,见value,指相同的力量,模糊,
前缀ambi,两边,周围,ience构成拉丁词ire的现在分词,it构成拉丁词ire的过去分词,ire,走,见commence,开始,adit,进,exit,出,
前缀ambi,两边,周围,词根it,走,
前缀ambi,两边,周围,词根it,走,向周围走,向外走,目标,
前缀ambi(在…周围)和基本动词agere(驾驶,引导)组成的复合词ambigere(争论,犹豫)派生的ambiguus(可改变的,摇摆的,有争议的),
来自PIE*antbhi,向两边的,向周围的,*ant,前面,同前缀ante,在前,*bhi,同bi,二,见ambivalence,ambiance,
英语单词ambition源自拉丁语ambitio,意思是“四处走”,其中的amb后来成为了英语词根,表示“走”,如救护车ambulance本意就是四处走的医院,ambition本来仅仅指以前的政客四处奔走发表演说拉选票的行为,在古罗马时期,谋求官职的人就像今天参加竞选活动的人一样,到处发表演说争取选票,政客拉选票自然是为了实现自己的政治抱负,所以ambition从“四处走”的基本意义中又引申出“野心,政治抱负”的含义,原本含有贬义,但现在已经变成中性词,既可以指“野心”,也可以指“雄心,志向”,
英语单词ambulance中的词根amb=walk,go,表示“走”,在18世纪之前,ambulance的本意是在战场上流动的医院,即所谓的“野战医院”,后来,在拿破仑发动的对欧战争中,他手下有位随军外科大夫DominiqueJeanLarry设计了一种用于急救的快速运载工具,随后,英国军队也采用了类似的伤员救护及运载工具,人们用英语ambulancecart或ambulancecargo来表示这种伤员救护及运载工具,进而将它们简称为ambulance,因此,ambulance一词的词义也就从“流动医院”转变为“救护车”了,
词根词缀,amb在…周围ig驾驶,引导uous形容词词尾
词根词缀,amb行走it行,走ious形容词词尾
词根词缀,amb行走it行,走ion名词词尾
词根词缀,amb在…周围ig驾驶,引导uity名词词尾
