defragment,計算機碎片清理

fragile--1
fragile,易碎的
fragile,易碎的,脆的；脆弱的,虛弱的
fragility,脆弱,虛弱

flair--0,天资,天赋
fragment--0--1
fragmentate,(使)成碎片(尤指爆炸),(使)碎裂
fragmentize,(使)裂成碎片,(使)分裂
fragment,碎片
fragment,碎片,片段
fragrance--1
fragrance,芳香
fragrant--1,芳香的
suffragan,副主教
suffragette,[,sʌfrə'dʒet]n.支持婦女選舉權的婦女。
suffragette,爭取婦女獲取投票權運動的人
suffrage(選舉權),通過叫喊或碎瓦片來表決
suffrage,['sʌfrɪdʒ]n.選舉權,投票,參政權
suffrage,選舉權,投票權
suffragist--1
suffragist,參政權擴大論者,婦女政權論者
來源於拉丁語中frangere(打破,打碎)的派生詞fragilis(易碎的)。
來自fragment,碎片。
來自PIE*bhrag,聞,詞源同brach(雌獵犬).其本義爲釋放氣味,聞,也包含放屁。所以該詞可能來自PIE*bhreg,分開,破開,詞源同break.即放出氣味。後詞義固定爲芳香。比較odorous,其原義爲聞,但詞義更多指難聞的,有臭味的。
來自PIE*bhreg,分開,破開,詞源同break,fraction.即破開的部分,碎片。
來自suffrage,投票,投票權,-ette,表陰性。字面意思即女性投票者,用於指20世紀初爭取婦女獲得投票權運動的人。
來自suffrage,投票,投票權,-ist,人。用於指提倡擴大參政權的人,原指鼓勵黑人獲取選舉權,後尤指鼓勵婦女獲取選取權。
來自拉丁語suffraganeus,助理,尤指主教助理,來自suffragium,投票,支持,詞源同suffrage,投票權。
來自拉丁語suffragium,投票,投票權,支持,來自suffragari,投票,給予支持,來自sub,在下,向上,-frag,碎開,碎片,詞源同break,fragment.來自古希臘古羅馬時期用碎瓦片碎骨片投票的習俗。比較ostracism,用碎骨片投票驅逐。
英語詞源字典
詞根詞綴,-frag-打破,打碎+-ile有…性質的
詞根詞綴,-frag-打破,打碎+-ile有…性質的(e略)+-ity名詞詞尾
詞根詞綴,-frag-打破,打碎+-ment名詞詞尾
詞根詞綴,-frag-打破,打碎+-ment名詞詞尾+-ate動詞詞尾
詞根詞綴,-frag-打破,打碎+-ment名詞詞尾+-ize動詞詞尾
該詞的英語詞源請訪問優詞詞源英文版,suffrage詞源,suffrage含義。
該詞進入英語後,最初表示“投票”。在美國1787年的憲法中,這個單詞首次用來表示“選舉權”。
這個單詞來自拉丁語suffragium(投票、投票權),該詞由sub(下面,在這裏變爲suf,與後面的f一致)+fragor(碰撞、叫喊、喧鬧)構成,意思是在底下大聲喊叫,通過聲音來表示贊同,就像我們現在舉手表示贊同一樣。還有一種說法認爲,fragor表示碎瓦片,意思是用碎瓦片來進行投票。不管是叫喊聲還是碎瓦片,fragor都與frangere(=英語中的break)有關,而frangere正是英語詞根frag(=break)的來源,含有frag的單詞有,fragment碎片、fragile易碎的、fraction分數等。
