#just=juxta靠近
#在古羅馬神話中,正義女神的名字叫做朱斯提提亞Justitia
#正義女神朱斯提提亞的塑像經常出現在法院中
#她的形象通常是身披白袍,雙眼蒙布,左手提一秤,右手舉一劍
just,公正公平的,正義的
justness,公正性

justice,法官
justifiable,可辯解的,有道理的,可證明為正當的
justification,正當理由的
justified,有正當理由的,情有可原的
justify--0,証明,是正當的,

jury,n,陪審團
juridical,adj,司法的
jurisdiction,司法權

unjust,正義,不公平的,不公義的
unjustifiable,毫無道理的
unjustified,未被證明為正當的
unjustly,不義地,不公平地

#adjust=ad(使)just(靠近)
adjust,調整,使適應於,校準,調整,適應於,校準

#in表示否定,jure=just公正的,對人不公正就是損害他人
injure,傷害,損害
injury,,傷害,損害
injustice,不公平,不公平的行為
injurious,有害的,致傷的
injuriously,有害地

#ab(離開)jure(發誓)→發誓離開→發誓放棄,
abjure--0,發誓放棄

#conjure來自拉丁語
#由con(共同)jure(發誓,詛咒)構成
conjure--0,想起,變出,記法,全部,發誓,法官逼你想起來全部都要發誓

#要求某人以上帝的名義起誓所述爲真
adjure,命令
adjuration--0,嚴令,懇求,祈求

#來自拉丁語periurium,僞誓,
#來自per,整個的,jur,發誓
perjure,作僞證,發假誓
perjury,作僞證,發假誓
