delay
delayed
delaying
delay,耽搁,延迟
lax--0
laxare
laxative,通便剂
lease,租约
relax
relaxation
relax,(使)放松,(使)松弛
relay,驿马,驿狗,接替,中转,接力
relay,驿马,驿狗,接替,中转,接力
release,解放,释放；发表,发行,发布
release,释放,松开,解雇,公布
release,释放,松开,解雇,公布
relish,享乐,乐趣；调味品
relish,调料,佐料,享受,喜欢
lessee,lessor
与词根-lax-(松弛,放松)同源
de-(离开)和动词laier(离开)组成的复合词delaier。动词laier的变体laissier是英语lease的词源,来源于拉丁语laxare(放松,松弛)。
古法语relais派生为relish。
古法语relaisser派生为release。
前缀re-(回)和基本动词laxare(放松,松弛)组成的复合动词relaxare(放松,松弛)。
来源于拉丁语动词laxare(放松,松弛),进入古法语为laissier(放松,放开),进入盎格鲁-诺曼底语为lesser,为合同条款中的“放行”之意,进入英语为lease。
来自中古法语relai,留下供接替的狗或其它动物,来自中法语relaier,留下,供替换的动物,来自re-,向后,laier,留下,词源同delay,可能来自拉丁语laxare,松开,词源同lax,relax.原指
来自中古法语relai,留下供接替的狗或其它动物,来自中法语relaier,留下,供替换的动物,来自re-,向后,laier,留下,词源同delay,可能来自拉丁语laxare,松开,词源同lax,relax.原指过去打猎时在中转站放置的供接替疲劳猎狗的备用狗,或驿站供接替的马。后引申诸多词义。由于词义与lay接近,拼写受到lay影响。
来自古法语relaisser,留下,留在后面,来自拉丁语relaxare,松开,松手,来自re-,向后,离开,laxare,松开,词源同lax,relax,release.拼写受-ish影响俗化。后引申词义味道,回味,后用于指调料,佐料,并引申动词词义享受,喜欢。
来自古法语relaissier,relesser,遗留,离开,留下,来自拉丁语relaxare,松开,松手,re-,向后,离开,laxare,松开,词源同lax,relax.引申诸相关词义。
来自古法语relaissier,relesser,遗留,离开,留下,来自拉丁语relaxare,松开,松手,re-,向后,离开,laxare,松开,词源同lax,relax.引申诸相关词义。
英语词源字典
词根词缀,de-离开+-lay(=-lax-)松弛,放松
词根词缀,re-回+-lax-松弛,放松
词根词缀,re-回+-leas-(=-lax-)松弛,放松+-e
词根词缀,re-回+-lish-(=-lax-)松弛,放松

