#cover,蓋子,封面,藉口,覆蓋,掩飾,保護,掩護,包括,覆蓋
covert,隱蔽的,隱藏處
overt,公開的,非祕密的
#covered,隱蔽著的,掩藏著的,有屋頂的
#covering,覆蓋物,遮避物,掩護的,掩蓋的
#discover,發現,找到,暴露,有所發現
#discovery,發現,發覺,被發現的事物
#recover,恢復,復原,使改過,痊癒,復原,重新獲得
#recovering,恢復
#uncover,揭露,揭開,暴露,脫,帽致敬,脫帽致敬,揭去蓋子
#undercover,祕密從事的,祕密的,被僱間諜活動的