#来自拉丁语rabere,发狂的
#en,进入,使,rage,狂怒,
enrage,狂怒
outrageous,憤怒的,駭人的
outrageously
outrage,愤怒,愤慨
outrage,暴行,冒犯,义愤,痛恨,严重的违法行为
rabid,發狂的,患狂犬病
rabies,狂犬病
rage,憤怒,狂怒
來源於通俗拉丁語rabies(瘋狂)和拉丁語動詞rabere(瘋狂,胡說),
來自古法語rage,生氣的,狂怒的,來自拉丁語rabere,發狂,發怒,來自PIE*rebh,暴力的,衝動的,可能來自PIE*reb,撕開,搶,詞源同rob,rip,字母b,g音變,比較ruby,red,rouge,
來自古法語rage,生氣的,狂怒的,來自拉丁語rabere,發狂,發怒,來自PIE*rebh,暴力的,衝動的,可能來自PIE*reb,撕開,搶,詞源同rob,rip,字母b,g音變,比較ruby,red,rouge,
來自拉丁語rabere,發狂的,詞源同rage,
來自拉丁語rabies,發狂,發瘋,來自拉丁語rabere,發狂的,詞源同rage,後用於指狂犬病,因狂犬病患者極端畏水,也稱爲hydrophobia,
前綴ad,去,往,詞根umb,影子,傘,見umbrella,傘,指輪廓,概述,
来自古法语outrage,伤害,损害,过度,无礼,来自拉丁语ultra,超过,词源同ultrasonic,ulterior,引申词义愤怒,愤慨等,
英语词源字典
词根词缀,out外rage愤怒

