||verb|verb|noun|adjective|adjective(a->n)|adverb||
|--------|---------|------------|-------------|--------------|-----------------|--------------|----------|
||-sist|-ing|-ence|-ent|-ency|-ently||
|a|assist|assisting|assistance|assistant|assistancy|assistantly|幫助|
|con|consist|consisting|consistence|consistent|consistency|consistently|組成|
|in-con||||inconsistent|inconsistency||不一致的|
|in|insist|||insistent|||堅持|
|per|persist||persistence|persistent||persistently|堅持|
|re|resist|resisting|resistance|resistant|resistancy||抵抗|
|sub|||subsistence||||生計|

#-sist站立
#assist,援助,幫助,援助,幫忙援助,幫助
#consisting,組成
#consistency,一致性
#consistence,濃度
#inconsistency,前後不一致,矛盾
#consistent--0,一致的
#inconsistent--0,不一致的
#insist,堅持,堅決要求,定要,堅持,堅決要求,定要
#insistent,內心堅持,堅持的,持續的,引人注目的
#persist,堅持,固執,持續
#persistence,名詞,堅持,固執,持續
#persistent--0,永久站立,持續不斷的,努力不懈的,持久的
#persistently,持久地,固執地
#resist,抵抗,耐得住,抵制,反抗防染劑
#resistance,抵抗力,反抗,耐力,反抗行動,阻力,反對,電阻
#resistant,形容詞,抵抗的,名詞,抵抗者,防染劑
#resisting,抵制,再次站立
#subsistence,最低限度的,生計