
trans(横过,越过)和dare(给)组成的复合动词tradere(交付),
1352年英国议会制定的StatuteofTreasons(叛逆法)将treason区分成hightreason(重判逆罪)和petittreason(轻判逆罪)两大类,Hightreason指叛国罪,即对国家或君主所犯下的各种罪行,petittreason指妻杀夫,仆杀主等行为,Treason原指“背叛”和“不忠”,但在现代英语一般多指“叛国(罪)”或“通敌(罪)”,Treason和tradition系同源姐妹词,都源于拉丁语tradere‘handover,deliver’的派生词traditio,不同的是,treason在13世纪转借自古法语traison,取的是traditio的引申义handingovertreacherously(背叛),而tradition则是以后直接借自拉丁语,取traditio的另一个引申义teaching(教导)或tradition(传统),另两个英语单词traitor(叛徒)和betray究其根源,亦源自拉丁语动词,
betray,背叛,出卖,泄露,失信于,辜负
betray,背叛,暴露
extradition,(根据条约或法令对逃犯等的)引渡
tradere
traditio
tradition,betray,treason
tradition,传统,al,形容词后缀,
tradition,传统,习俗
tradition,传统,惯例
traditional,传统的,ism,主义,
traditional,传统的,ist,人,
traditional,传统的,守旧的
traditionalism,传统主义
traditionalist,传统主义者
traitor(叛徒,卖国贼,背信弃义者)
traitor,betray,treason
traitor,tradition,betray
traitor,tradition,treason
traitor,卖国贼,叛徒
traitor,背叛者,叛徒
tray,背叛
treason
treason,不忠,叛逆,谋反,叛国(罪)
treason,叛国(罪)
treason,叛国罪
【发音释义】,[bɪ'treɪ]vt,背叛,出卖,暴露
【结构分析】,betray=be(前缀)tray(交出)→出卖,背叛→暴露
【衍生词】,betrayal(背叛,出卖,辜负,暴露)
【词源解释】,tray←拉丁语tradere(交出,移交)
来自中古英语trayen,背叛,来自古法语trair,背叛,来自拉丁语tradere,转移,移交,词源同tradition,treason,betray,该词基本上已废弃,主要见于复合词betray,
来自古法语tradicion,转移,移交,交付,来自拉丁语tradere,转移,交付,来自tra,转移,
来自古法语tradicion,转移,移交,交付,来自拉丁语tradere,转移,交付,来自tra,转移,dare,给予,来自PIE*do,给,给予,词源同donate,edit,引申词义传统,习俗等,
来自古法语traison,背叛,来自拉丁语traditionem,移交,投降,来自拉丁语tradere,转移,移交,词源同tradition,betray,引申词义叛国罪,
来自古法语traitor,叛徒,来自(缩写自)拉丁语traditor,叛徒,来自tradere,转给,移交,投降,词源同treason,betray,该词与tradition为对词关系,但词义完全不同,
英语词源字典
词根词缀,ex出tra转变,转换dit给ion名词词尾
